### ISSUE TITLE
[PE-D][Tester A] Incorrect Help Window screenshot in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-4/tp#132] opened 2022-10-28 18:23 UTC
Screenshot of help window in user guide shows the URL to the upstream AB3 user guide instead of the product's user guide.

![image.png](https://raw.githubusercontent.com/Benjamin-Sim/ped/main/files/2766d1e8-71d4-4196-b2a9-7e18a0eef2fa.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Benjamin-Sim/ped#3

**Comment by gowribhat** [comment] 2022-10-29 06:26
Duplicate of #133

**Closed as completed by gowribhat** 2022-10-29 06:26 UTC
Labels: duplicate
