### ISSUE TITLE
[PE-D][Tester D] Help command brings out URL that leads to AB-3 UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-4/tp#167] opened 2022-10-29 04:16 UTC
No details provided by bug reporter.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: fungusta/ped#3

**Comment by gowribhat** [comment] 2022-10-29 06:20
Duplicate of #139

**Closed as completed by gowribhat** 2022-10-29 06:20 UTC
Labels: duplicate
