### ISSUE TITLE
[PE-D][Tester B] Incorrect link to help page

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-4/tp#175] opened 2022-10-29 04:52 UTC
The link leads the user to the original AB3 User Guide instead of the product's
![image.png](https://raw.githubusercontent.com/JasonCP14/ped/main/files/d06a5a38-8cab-4239-a843-eb5fd95b6275.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: JasonCP14/ped#18

**Comment by gowribhat** [comment] 2022-10-29 06:22
Duplicate of #139

**Closed as completed by gowribhat** 2022-10-29 06:22 UTC
Labels: duplicate
